export const stations = [
  { id: "A826", name: "ALEGRETE" },
  { id: "A827", name: "BAGE" },
  { id: "A840", name: "BENTO GONCALVES" },
  { id: "A812", name: "CACAPAVA DO SUL" },
  { id: "A838", name: "CAMAQUA" },
  { id: "A897", name: "CAMBARA DO SUL" },
  //{ id: 'A884', name: 'CAMPO BOM' },
  //{ id: 'A879', name: 'CANELA' },
  { id: "A811", name: "CANGUCU" },
  { id: "A887", name: "CAPAO DO LEAO (PELOTAS)" },
  { id: "A853", name: "CRUZ ALTA" },
  { id: "A881", name: "DOM PEDRITO" },
  { id: "A893", name: "ENCRUZILHADA DO SUL" },
  { id: "A828", name: "ERECHIM" },
  { id: "A854", name: "FREDERICO WESTPHALEN" },
  { id: "A883", name: "IBIRUBA" },
  { id: "A836", name: "JAGUARAO" },
  { id: "A844", name: "LAGOA VERMELHA" },
  //{ id: 'A878', name: 'MOSTARDAS' },
  { id: "A856", name: "PALMEIRA DAS MISSOES" },
  { id: "A839", name: "PASSO FUNDO" },
  { id: "A801", name: "PORTO ALEGRE - JARDIM BOTANICO" },
  { id: "B807", name: "PORTO ALEGRE- BELEM NOVO" },
  { id: "A831", name: "QUARAI" },
  { id: "A802", name: "RIO GRANDE" },
  { id: "A813", name: "RIO PARDO" },
  { id: "A803", name: "SANTA MARIA" },
  { id: "A810", name: "SANTA ROSA" },
  { id: "A804", name: "SANTANA DO LIVRAMENTO" },
  { id: "A833", name: "SANTIAGO" },
  { id: "A805", name: "SANTO AUGUSTO" },
  { id: "A830", name: "SAO BORJA" },
  { id: "A832", name: "SAO GABRIEL" },
  { id: "A829", name: "SAO JOSE DOS AUSENTES" },
  { id: "A852", name: "SAO LUIZ GONZAGA" },
  { id: "A889", name: "SAO VICENTE DO SUL" },
  { id: "A894", name: "SERAFINA CORREA" },
  { id: "A837", name: "SOLEDADE" },
  { id: "A899", name: "SANTA VITORIA DO PALMAR  - BARRA DO CHUÍ" },
  { id: "A882", name: "TEUTONIA" },
  { id: "A808", name: "TORRES" },
  //{ id: 'A834', name: 'TRAMANDAI' },
  { id: "A886", name: "TUPANCIRETA" },
  { id: "A809", name: "URUGUAIANA" },
  { id: "A880", name: "VACARIA" },
];
